-- MySQL Script generated by MySQL Workbench
-- 03/16/16 18:31:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lista
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lista` DEFAULT CHARACTER SET utf8 ;
USE `lista` ;

-- -----------------------------------------------------
-- Table `lista`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `foto` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `foto` VARCHAR(45) NULL DEFAULT NULL,
  `link` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista`.`lista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `link` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_lista_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_lista_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `lista`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista`.`item` (
  `produto_id` INT NOT NULL,
  `lista_id` INT NOT NULL,
  PRIMARY KEY (`produto_id`, `lista_id`),
  INDEX `fk_item_lista1_idx` (`lista_id` ASC),
  CONSTRAINT `fk_item_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `lista`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_lista1`
    FOREIGN KEY (`lista_id`)
    REFERENCES `lista`.`lista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
